### PR TITLE
Add Danby DAC060EB7WDB

### PR DESCRIPTION
**Pull request by technobulb**
This was added to 
https://github.com/flipperdevices/flipperzero-firmware/ already so I am not sure if this is necessary.
I can also get you High Fan/Lo Fan and more commands if requested

### CODE REVIEW

**Comment by technobulb** [comment]
Hi any update on this?

**Comment by UberGuidoZ** [comment]
I don't get around here as much as I used to and appear to be the only maintainer. =) Thanks for your patience.

**Review by Mjefoester — COMMENTED** [review]
thank you

**Review by Mjefoester — COMMENTED** [review]
😀

**Pull request merged**
