### PR TITLE
Fixed Honeywell_HO-5500RE

### PR DESCRIPTION
**Pull request by amazing4u**
Hi,

I fixed the honeywell HO 5500RE signal

### CODE REVIEW

**Comment by UberGuidoZ** [comment]
Confirmed, thanks for your patience!

**Comment by amec0e** [comment]
The Prior signals was also confirmed and working, not quite sure what was wrong with this, captured and tested with my unit.

**Comment by amazing4u** [comment]
The prior request did not work properly with my device. If i remember right, only the power was working.

So i captured and tested the new signals from my remote.

**Comment by amec0e** [comment]
Ah okay that's absolutely fine thank you for fixing it!

**Comment by UberGuidoZ** [comment]
I thought about keeping a copy of both since they were quite different. Maybe a v1 and a v2?

**Pull request merged**
