### PR TITLE
Update Actions

### PR DESCRIPTION
**Pull request by PartTimeLegend**
You could also use [Renovate](https://github.com/apps/renovate) to manage these in future.

### CODE REVIEW

**Comment by UberGuidoZ** [comment]
Will review. Thank you!

**Comment by darmiel** [comment]
Thanks!
I've used `v29.0.7` for the `changed-files`-action because the newer version didn't work for me when adding the workflow (but maybe my problem got already fixed). I'll try to test this when I got some time 🙂

**Comment by PartTimeLegend** [comment]
I would definitely recommend looking at Renovate. It killed my usage minutes at first but now a few PRs a month get everything up to date.

**Comment by darmiel** [comment]
Tested & updated the dependencies to the newest version in https://github.com/logickworkshop/Flipper-IRDB/pull/511

/cc @UberGuidoZ: this PR can be closed :)

**Pull request closed without merging**
