### PR TITLE
new remotes! 

### LINKED ISSUE #812: Request: Ffalcon_SF1_Smart_TV.ir - Add navigation buttons (UP, DOWN, LEFT, RIGHT, ENTER)

### PR DESCRIPTION
**Pull request by jaylikesbunda**
### TVs:
- Soniq QSP500TV6
- Soniq Z24Z15B
- Kogan KALED50XU9210STB
- Hisense 58R5
- Hisense 55E7KQ

### Fans:
- Mistral FTFYG07R

### Blu-ray Players:
- Philips BDP7302
- Philips BDP2700
- Philips BDP2501F7
- Vizio VBR220
- Sharp BDHP20
- Pioneer BDP43FD
- Pioneer BDP150
- Panasonic DMRBWT720
- LG BH9520TW
- Samsung BDE5300
- Sony BDPBX120
- Sony BDPS770
- Samsung BDD7500
- Panasonic DMPBDT167
- Sony BDPS1700
- Sony UBPX700
- Panasonic DPUB820
- Panasonic DPUB420
- Vizio VBR333
- Sony BDPS360
- OPPO BDP103
- Sylvania SDVD1111
- Samsung UBDK8500
- LG UBK80
- NAD T557
- Yamaha BDS667
- Marantz BD8002
- LG BD690
- JVC XVBP1 
- Soniq B100
- Pioneer BDP320

### VCRs:
- Sony SLV70HF
- Sony SLV789HF
- Sony SLVD201P
- Sony SLVM88
- JVC HRS7900U
- Panasonic AG7350
- Memorex MVR4040A

### Soundbars:
- LG NB5541
- JVC THBY370A
- Toshiba SBX4250
- RCA RTS7110B2
- Hitachi HSB40B16
- Hisense HS215

note: i pr'd the pioneer protocol into @darmiel's repo not sure if he's very active though 
EDIT: thank you daniel <3

resolves #812

### CODE REVIEW

**Comment by darmiel** [comment]
> note: i pr'd the pioneer protocol into @darmiel's repo not sure if he's very active though

Thanks for the update! I've merged it. You can try closing and reopening the PR to verify it with the new protocol. 😊

**Comment by darmiel** [comment]
Can this be closed in favor of #813 ?

**Comment by jaylikesbunda** [comment]
> Can this be closed in favor of #813 ?

all new IRDB additions are in this PR
#813 is just running existing files (not additions through)

**Comment by darmiel** [comment]
> > Can this be closed in favor of #813 ?
> 
> all new IRDB additions are in this PR #813 is just running existing files (not additions through)

I see! I saw a few new files added in #813:

* Blu-Ray/Samsung/Samsung_BDD7500.ir
* Blu-Ray/Samsung/Samsung_BDE5300.ir
* Blu-Ray/Sharp/Sharp_BDHP20.ir
* Blu-Ray/Vizio/Vizio_VBR220.ir
* Fans/Mistral/Mistral_MTFYG07R.ir
* Miscellaneous/Elune_Vision_Motorized_Projector_Screen/Elune_Vision_Motorized_Projector_Scr.ir
* VCR/JVC/JVC_HR-A591U.ir
* VCR/JVC/JVC_HR-J700E.ir
* VCR/JVC/JVC_HR-S2902U.ir

a few of them look like they have been renamed in this PR. Was that what you wanted? If so, I can go ahead and merge #813

**Comment by jaylikesbunda** [comment]
> * Blu-Ray/Samsung/Samsung_BDD7500.ir
> 
> * Blu-Ray/Samsung/Samsung_BDE5300.ir
> 
> * Blu-Ray/Sharp/Sharp_BDHP20.ir
> 
> * Blu-Ray/Vizio/Vizio_VBR220.ir
> 
> * Fans/Mistral/Mistral_MTFYG07R.ir
Ah I see.
```
Blu-Ray/Samsung/Samsung_BDD7500.ir
Blu-Ray/Samsung/Samsung_BDE5300.ir
Blu-Ray/Sharp/Sharp_BDHP20.ir
Blu-Ray/Vizio/Vizio_VBR220.ir
Fans/Mistral/Mistral_MTFYG07R.ir
```
were accidental additions and
```
VCR/JVC/JVC_HR-A591U.ir
VCR/JVC/JVC_HR-J700E.ir
VCR/JVC/JVC_HR-S2902U.ir
```
were renamed to use device model instead of remote for file name on purpose yes
not sure what the misc file is

**Review by darmiel — APPROVED** [review]

**Pull request merged**
